# Generated by Django 5.2.5 on 2025-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_classes_conducted', models.IntegerField(default=0)),
                ('classes_attended', models.IntegerField(default=0)),
                ('attendance_percentage', models.CharField(default='N/A', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
