# Generated by Django 5.2.5 on 2025-08-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancedata',
            name='attendance_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
