# Generated by Django 5.2.5 on 2025-08-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_dashboard.userprofile'),
        ),
    ]
