# Generated by Django 5.2.5 on 2025-08-16 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_dashboard', '0004_attendancedata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedata',
            unique_together={('user', 'date')},
        ),
    ]
